services:
  - type: web
    name: my-netflix
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node server.js
    disk:
      name: netflix-data
      mountPath: /var/data/netflix
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: APP_PASSWORD
        sync: false
      - key: DATA_ROOT
        value: /var/data/netflix
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        value: my_netflix
      - key: MYSQL_URL
        sync: false
      - key: MYSQL_HOST
        sync: false
      - key: MYSQL_PORT
        value: 3306
      - key: MYSQL_USER
        sync: false
      - key: MYSQL_PASSWORD
        sync: false
      - key: MYSQL_DATABASE
        value: my_netflix
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
